"""NSE F&O universe — indices + ~190 active stock derivatives.

`HIGH_PRIORITY` symbols are polled every 60s; the broader universe is polled
every 5 minutes so we don't blow through Fyers rate limits.

Source: NSE F&O list (https://www.nseindia.com/products-services/equity-derivatives-list-underlyings).
This list is current to Jan 2026 — refresh quarterly as NSE adds/removes
stocks from the F&O segment.
"""
from __future__ import annotations

# 8 indices — always tier-1
INDICES = [
    "NSE:NIFTY50-INDEX",
    "NSE:NIFTYBANK-INDEX",
    "NSE:FINNIFTY-INDEX",
    "NSE:MIDCPNIFTY-INDEX",
    "NSE:NIFTYNXT50-INDEX",
    "BSE:SENSEX-INDEX",
    "BSE:BANKEX-INDEX",
]

# Tier-1: highest OI / volume stock options — poll every minute
HIGH_PRIORITY_STOCKS = [
    "NSE:RELIANCE-EQ", "NSE:HDFCBANK-EQ", "NSE:ICICIBANK-EQ", "NSE:INFY-EQ",
    "NSE:TCS-EQ", "NSE:SBIN-EQ", "NSE:BHARTIARTL-EQ", "NSE:AXISBANK-EQ",
    "NSE:KOTAKBANK-EQ", "NSE:LT-EQ", "NSE:ITC-EQ", "NSE:HINDUNILVR-EQ",
    "NSE:BAJFINANCE-EQ", "NSE:MARUTI-EQ", "NSE:M&M-EQ", "NSE:TATAMOTORS-EQ",
    "NSE:ADANIENT-EQ", "NSE:ADANIPORTS-EQ", "NSE:TATASTEEL-EQ", "NSE:HCLTECH-EQ",
    "NSE:WIPRO-EQ", "NSE:SUNPHARMA-EQ", "NSE:ULTRACEMCO-EQ", "NSE:JSWSTEEL-EQ",
    "NSE:POWERGRID-EQ", "NSE:NTPC-EQ", "NSE:ONGC-EQ", "NSE:INDUSINDBK-EQ",
    "NSE:NESTLEIND-EQ", "NSE:ASIANPAINT-EQ",
]

# Tier-2: broader F&O universe — poll every 5 minutes
LOW_PRIORITY_STOCKS = [
    "NSE:ABB-EQ", "NSE:ACC-EQ", "NSE:ADANIGREEN-EQ", "NSE:ALKEM-EQ",
    "NSE:AMBUJACEM-EQ", "NSE:APOLLOHOSP-EQ", "NSE:APOLLOTYRE-EQ",
    "NSE:ASHOKLEY-EQ", "NSE:ASTRAL-EQ", "NSE:AUBANK-EQ",
    "NSE:AUROPHARMA-EQ", "NSE:BAJAJ-AUTO-EQ", "NSE:BAJAJFINSV-EQ",
    "NSE:BALKRISIND-EQ", "NSE:BANDHANBNK-EQ", "NSE:BANKBARODA-EQ",
    "NSE:BATAINDIA-EQ", "NSE:BEL-EQ", "NSE:BERGEPAINT-EQ", "NSE:BHARATFORG-EQ",
    "NSE:BHEL-EQ", "NSE:BIOCON-EQ", "NSE:BOSCHLTD-EQ", "NSE:BPCL-EQ",
    "NSE:BRITANNIA-EQ", "NSE:CANBK-EQ", "NSE:CHAMBLFERT-EQ", "NSE:CHOLAFIN-EQ",
    "NSE:CIPLA-EQ", "NSE:COALINDIA-EQ", "NSE:COFORGE-EQ", "NSE:COLPAL-EQ",
    "NSE:CONCOR-EQ", "NSE:COROMANDEL-EQ", "NSE:CROMPTON-EQ", "NSE:CUB-EQ",
    "NSE:CUMMINSIND-EQ", "NSE:DABUR-EQ", "NSE:DALBHARAT-EQ", "NSE:DEEPAKNTR-EQ",
    "NSE:DELTACORP-EQ", "NSE:DIVISLAB-EQ", "NSE:DIXON-EQ", "NSE:DLF-EQ",
    "NSE:DRREDDY-EQ", "NSE:EICHERMOT-EQ", "NSE:ESCORTS-EQ", "NSE:EXIDEIND-EQ",
    "NSE:FEDERALBNK-EQ", "NSE:GAIL-EQ", "NSE:GLENMARK-EQ", "NSE:GMRINFRA-EQ",
    "NSE:GNFC-EQ", "NSE:GODREJCP-EQ", "NSE:GODREJPROP-EQ", "NSE:GRANULES-EQ",
    "NSE:GRASIM-EQ", "NSE:GUJGASLTD-EQ", "NSE:HAL-EQ", "NSE:HAVELLS-EQ",
    "NSE:HDFCAMC-EQ", "NSE:HDFCLIFE-EQ", "NSE:HEROMOTOCO-EQ", "NSE:HINDALCO-EQ",
    "NSE:HINDCOPPER-EQ", "NSE:HINDPETRO-EQ", "NSE:IBULHSGFIN-EQ", "NSE:ICICIGI-EQ",
    "NSE:ICICIPRULI-EQ", "NSE:IDEA-EQ", "NSE:IDFC-EQ", "NSE:IDFCFIRSTB-EQ",
    "NSE:IEX-EQ", "NSE:IGL-EQ", "NSE:INDIACEM-EQ", "NSE:INDIAMART-EQ",
    "NSE:INDHOTEL-EQ", "NSE:INDIGO-EQ", "NSE:IOC-EQ", "NSE:IPCALAB-EQ",
    "NSE:IRCTC-EQ", "NSE:JINDALSTEL-EQ", "NSE:JKCEMENT-EQ", "NSE:JUBLFOOD-EQ",
    "NSE:LALPATHLAB-EQ", "NSE:LAURUSLABS-EQ", "NSE:LICHSGFIN-EQ", "NSE:LTF-EQ",
    "NSE:LTIM-EQ", "NSE:LTTS-EQ", "NSE:LUPIN-EQ", "NSE:MANAPPURAM-EQ",
    "NSE:MARICO-EQ", "NSE:MCDOWELL-N-EQ", "NSE:MCX-EQ", "NSE:METROPOLIS-EQ",
    "NSE:MFSL-EQ", "NSE:MGL-EQ", "NSE:MOTHERSON-EQ", "NSE:MPHASIS-EQ",
    "NSE:MRF-EQ", "NSE:MUTHOOTFIN-EQ", "NSE:NATIONALUM-EQ", "NSE:NAUKRI-EQ",
    "NSE:NAVINFLUOR-EQ", "NSE:NMDC-EQ", "NSE:OBEROIRLTY-EQ", "NSE:OFSS-EQ",
    "NSE:OIL-EQ", "NSE:PAGEIND-EQ", "NSE:PEL-EQ", "NSE:PERSISTENT-EQ",
    "NSE:PETRONET-EQ", "NSE:PFC-EQ", "NSE:PIDILITIND-EQ", "NSE:PIIND-EQ",
    "NSE:PNB-EQ", "NSE:POLYCAB-EQ", "NSE:POONAWALLA-EQ", "NSE:PVRINOX-EQ",
    "NSE:RAMCOCEM-EQ", "NSE:RBLBANK-EQ", "NSE:RECLTD-EQ", "NSE:SAIL-EQ",
    "NSE:SBICARD-EQ", "NSE:SBILIFE-EQ", "NSE:SHREECEM-EQ", "NSE:SHRIRAMFIN-EQ",
    "NSE:SIEMENS-EQ", "NSE:SRF-EQ", "NSE:SUNTV-EQ", "NSE:SYNGENE-EQ",
    "NSE:TATACHEM-EQ", "NSE:TATACOMM-EQ", "NSE:TATACONSUM-EQ", "NSE:TATAPOWER-EQ",
    "NSE:TECHM-EQ", "NSE:TITAN-EQ", "NSE:TORNTPHARM-EQ", "NSE:TORNTPOWER-EQ",
    "NSE:TRENT-EQ", "NSE:TVSMOTOR-EQ", "NSE:UBL-EQ", "NSE:UNITDSPR-EQ",
    "NSE:UPL-EQ", "NSE:VEDL-EQ", "NSE:VOLTAS-EQ", "NSE:ZEEL-EQ",
    "NSE:ZYDUSLIFE-EQ",
]


def all_high_priority() -> list[str]:
    return INDICES + HIGH_PRIORITY_STOCKS


def all_low_priority() -> list[str]:
    return LOW_PRIORITY_STOCKS


def all_fno_symbols() -> list[str]:
    return INDICES + HIGH_PRIORITY_STOCKS + LOW_PRIORITY_STOCKS
